### ISSUE TITLE
Powershell gallery

### ISSUE THREAD

**Issue by TerribleDev** [SumoLogic/sumo-powershell-sdk#4]
You may want to consider publishing this to the powershell gallery. https://www.powershellgallery.com basically apt for powershell modules and what not.

**Comment by the-chris-mitchell** [comment]
+1, would be really good for specifying sumo-powershell-sdk as a requirement for other modules, as this now seems to be possible with PowerShellGet (without having to use psget)

**Comment by sbe-arg** [comment]
proposed refactor of module to make psgallery friendly here >>> https://github.com/SumoLogic/sumo-powershell-sdk/pull/10

**Comment by bin3377** [comment]
https://github.com/SumoLogic/sumo-powershell-sdk/tree/ps_gallery
