### ISSUE TITLE
Can you create a source with set-source

### ISSUE THREAD

**Issue by rickjuryxero** [SumoLogic/sumo-powershell-sdk#8]
I was reading through the code for get-source, set-source etc but not sure it's possible with the sdk to create a source.

https://github.com/SumoLogic/sumo-powershell-sdk/blob/master/sumologic/SumoLogic.psm1#L355

to create a source you need to POST and set-source only has GET or PUT methods e.g
Method: POST Path: /collectors/[collectorId]/sources

It would be nice to be able to create sources (with some logic to test if it already exists by name or not on that collector and if so to switch to update instead).

**Comment by sbe-arg** [comment]
Hey @rickjuryxero have you tried with a fork and changing https://github.com/SumoLogic/sumo-powershell-sdk/blob/master/sumologic/SumoLogic.psm1#L375 to POST, I think the enpoint used to accept PUT but changed here https://help.sumologic.com/APIs/01Collector-Management-API/Source-API updated on date March 2th 2018. I do remember using `Set-Source` and working fine a while ago (about 1y ago).
